language: objective-c
before_install:
    - (ruby --version)
    - (motion --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update
script: "./run-tests.sh"